#!/usr/bin/env python3
"""Create a disposable fake Claude Code home (~/.claude-shaped) for Attaché
tests and smokes, plus a fake `claude` executable that mimics the real CLI's
verified `-p --resume <id> --output-format json "<text>"` contract (INF-241).

Mirrors scripts/create-fake-codex-home.py: same CLI-flag style, same
disposable-home approach, same "print a JSON summary to stdout" convention so
shell smokes can pull fields out with `python3 -c` or `jq`.

Usage (unit tests / smokes both use the printed `ATTACHE_FAKE_CLAUDE_HOME`
env var, not $HOME, because AgentResumeDeliveryAdapter's default spawn always
overrides $HOME to the real user's home before shelling out):

    python3 scripts/create-fake-claude-home.py --home /tmp/x --nonce N > meta.json
    export ATTACHE_FAKE_CLAUDE_HOME=/tmp/x
    export PATH="$(python3 -c 'import json,sys;print(json.load(open("meta.json"))["fake_claude_bin_dir"])"):$PATH"
    claude -p --resume <target_session_id> --output-format json "hello"
"""
import argparse
import json
import os
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Embedded verbatim as the fake `claude` executable. Kept as a single string so
# the whole fixture (data + stub CLI) lives in one script, like its Codex
# counterpart.
FAKE_CLAUDE_SCRIPT = '''#!/usr/bin/env python3
"""Fake `claude` CLI for Attaché tests (generated by create-fake-claude-home.py,
INF-241). Mimics the real CLI's verified contract exactly:

  claude -p --resume <sessionId> --output-format json "<text>"

Success: a single JSON object on stdout, exit 0. Unknown/stale session id:
plain-text "No conversation found with session ID: <id>" on stderr, exit 1,
empty stdout. Do not hand-edit; regenerate via create-fake-claude-home.py.

Failure-mode simulation (tests only; unset all of these for real-contract
behavior):
  ATTACHE_FAKE_CLAUDE_MODE=hang        sleep past any reasonable test timeout
                                       (ATTACHE_FAKE_CLAUDE_HANG_SECONDS,
                                       default 5), then behave normally.
  ATTACHE_FAKE_CLAUDE_MODE=no_evidence exit 0 but append nothing and print
                                       nothing: the silent no-op delivery
                                       success gap this fixture exists to
                                       expose (see the 2026-07-10 app review,
                                       section 1, item 1).
  ATTACHE_FAKE_CLAUDE_MODE=exit_code   exit nonzero with a custom stderr
                                       (ATTACHE_FAKE_CLAUDE_EXIT_CODE, default
                                       1; ATTACHE_FAKE_CLAUDE_STDERR, default
                                       message).

$ATTACHE_FAKE_CLAUDE_HOME (not $HOME: AgentResumeDeliveryAdapter's default
spawn always overrides $HOME to the real user's home before it shells out)
points at the disposable home created by create-fake-claude-home.py; the
fixture manifest lives at <that>/.claude/attache-fake-claude-fixtures.json.
Falls back to $HOME for standalone/manual use.
"""
import json
import os
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path


def iso(dt):
    return dt.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def fake_home():
    override = os.environ.get("ATTACHE_FAKE_CLAUDE_HOME")
    if override:
        return Path(override)
    return Path(os.environ.get("HOME", str(Path.home())))


def manifest_path():
    return fake_home() / ".claude" / "attache-fake-claude-fixtures.json"


def load_manifest():
    try:
        return json.loads(manifest_path().read_text(encoding="utf-8"))
    except Exception:
        return {}


def parse_args(argv):
    session_id = None
    i = 0
    while i < len(argv):
        if argv[i] == "--resume" and i + 1 < len(argv):
            session_id = argv[i + 1]
            i += 2
            continue
        i += 1
    text = argv[-1] if argv else None
    return session_id, text


def append_turn(session_file, text, result_text):
    now = datetime.now(timezone.utc)
    lines = [
        json.dumps(
            {"type": "user", "timestamp": iso(now), "message": {"role": "user", "content": text or ""}},
            separators=(",", ":"),
        ),
        json.dumps(
            {
                "type": "assistant",
                "timestamp": iso(now),
                "message": {"role": "assistant", "content": [{"type": "text", "text": result_text}]},
            },
            separators=(",", ":"),
        ),
    ]
    with open(session_file, "a", encoding="utf-8") as f:
        f.write("\\n".join(lines) + "\\n")


def main():
    argv = sys.argv[1:]
    session_id, text = parse_args(argv)
    mode = os.environ.get("ATTACHE_FAKE_CLAUDE_MODE", "").strip()

    if mode == "hang":
        time.sleep(float(os.environ.get("ATTACHE_FAKE_CLAUDE_HANG_SECONDS", "5")))

    if mode == "exit_code":
        code = int(os.environ.get("ATTACHE_FAKE_CLAUDE_EXIT_CODE", "1"))
        message = os.environ.get("ATTACHE_FAKE_CLAUDE_STDERR", "fake claude: simulated failure")
        sys.stderr.write(message)
        sys.exit(code)

    manifest = load_manifest()
    session_file = manifest.get(session_id) if session_id else None

    if not session_id or not session_file or not Path(session_file).exists():
        sys.stderr.write(f"No conversation found with session ID: {session_id}")
        sys.exit(1)

    if mode == "no_evidence":
        # Exit 0 like a real success, but never touch the transcript and print
        # nothing: a silent no-op that AgentResumeDeliveryAdapter.deliver()
        # currently cannot distinguish from a real success (it only checks the
        # exit code).
        sys.exit(0)

    result_text = f"DONE: {text}" if text else "DONE"
    append_turn(session_file, text, result_text)

    payload = {
        "type": "result",
        "subtype": "success",
        "is_error": False,
        "api_error_status": None,
        "duration_ms": 1605,
        "duration_api_ms": 1550,
        "ttft_ms": 1534,
        "ttft_stream_ms": 1090,
        "time_to_request_ms": 37,
        "num_turns": 1,
        "result": result_text,
        "stop_reason": "end_turn",
        "session_id": session_id,
        "total_cost_usd": 0.0819288,
        "usage": {
            "input_tokens": 2,
            "cache_creation_input_tokens": 12085,
            "cache_read_input_tokens": 31126,
            "output_tokens": 5,
        },
        "permission_denials": [],
        "terminal_reason": "completed",
        "fast_mode_state": "off",
        "uuid": str(uuid.uuid4()),
    }
    sys.stdout.write(json.dumps(payload, separators=(",", ":")))
    sys.exit(0)


if __name__ == "__main__":
    main()
'''


def iso(dt):
    return dt.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def slug_for_cwd(cwd):
    # Mirrors Claude Code's real project-directory encoding: every path
    # separator becomes a dash (e.g. /Users/x/y -> -Users-x-y).
    return cwd.replace("/", "-")


def write_session(path, cwd, title, body):
    """A baseline (pre-delivery) session: one user turn and one completed,
    non-sidechain assistant turn, matching the exact shape
    SessionDeliveryReadinessClassifier.scanClaude expects for a completed turn
    (see testDeliveryReadinessHandlesClaudeCompletedAndPendingTurns in
    Tests/AttacheAppTests/TwoWayDeliveryAdapterTests.swift)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc)
    lines = [
        {
            "type": "user",
            "cwd": cwd,
            "timestamp": iso(now),
            "message": {"role": "user", "content": title},
        },
        {
            "type": "assistant",
            "cwd": cwd,
            "timestamp": iso(now + timedelta(seconds=1)),
            "message": {"role": "assistant", "content": [{"type": "text", "text": body}]},
        },
    ]
    path.write_text("\n".join(json.dumps(line, separators=(",", ":")) for line in lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Create a disposable fake Claude Code home (~/.claude-shaped) plus a fake `claude` CLI for Attaché tests."
    )
    parser.add_argument("--home", required=True, help="Disposable directory to use as the fake home; creates <home>/.claude/... and <home>/bin/claude inside it.")
    parser.add_argument("--nonce", required=True)
    parser.add_argument("--count", type=int, default=1)
    parser.add_argument("--needle", default="")
    parser.add_argument("--target-title", default="")
    args = parser.parse_args()

    home = Path(args.home)
    claude_home = home / ".claude"
    projects = claude_home / "projects"
    bin_dir = home / "bin"
    for directory in [projects, bin_dir]:
        directory.mkdir(parents=True, exist_ok=True)

    count = max(1, args.count)
    target_index = min(count - 1, max(0, count // 2))
    cwd = f"/tmp/attache-fake-claude-{args.nonce}"
    slug = slug_for_cwd(cwd)
    project_dir = projects / slug
    needle = args.needle or f"ATTACHE_LOAD_NEEDLE_{args.nonce}"
    target_title = args.target_title or f"Load smoke target {args.nonce}"

    manifest = {}
    target_session_id = ""
    target_session_file = ""

    for i in range(count):
        session_id = str(uuid.uuid4())
        path = project_dir / f"{session_id}.jsonl"
        if i == target_index:
            title = target_title
            body = f"{needle} target transcript for {args.nonce}."
            target_session_id = session_id
            target_session_file = str(path)
        else:
            title = f"Load smoke background {args.nonce} {i:03d}"
            body = f"Background fake Claude transcript {i:03d} for {args.nonce}."
        write_session(path, cwd, title, body)
        manifest[session_id] = str(path)

    manifest_file = claude_home / "attache-fake-claude-fixtures.json"
    manifest_file.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    os.chmod(manifest_file, 0o600)

    fake_claude_executable = bin_dir / "claude"
    fake_claude_executable.write_text(FAKE_CLAUDE_SCRIPT, encoding="utf-8")
    os.chmod(fake_claude_executable, 0o700)

    print(
        json.dumps(
            {
                "home": str(home),
                "claude_home": str(claude_home),
                "fake_claude_bin_dir": str(bin_dir),
                "fake_claude_executable": str(fake_claude_executable),
                "manifest_file": str(manifest_file),
                "target_session_id": target_session_id,
                "target_session_file": target_session_file,
                "target_title": target_title,
                "needle": needle,
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
