#!/usr/bin/env python3
"""Create a disposable fake Codex home for Attaché tests and smokes, plus (INF-250)
a fake `codex` executable that mimics the real CLI's verified resume contract:

  codex exec resume --skip-git-repo-check --json <sessionId> <text>

Unlike scripts/create-fake-claude-home.py's fake `claude`, which callers put on
PATH, this fake executable must be installed at the fixed path
CLILanguageModel.candidatePath() checks first for "codex"
(~/.local/bin/codex): AgentResumeDeliveryAdapter's default locateExecutable
resolves the CLI from a short list of absolute locations, not a caller-supplied
PATH override, so shadowing the real CLI means placing this file at that exact
path for the duration of the smoke (see scripts/agent-destination-smoke.sh,
which backs up and restores whatever was there first).
"""
import argparse
import json
import os
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Embedded verbatim as the fake `codex` executable, mirroring
# create-fake-claude-home.py's FAKE_CLAUDE_SCRIPT approach: the whole fixture
# (data + stub CLI) lives in one script.
FAKE_CODEX_SCRIPT = '''#!/usr/bin/env python3
"""Fake `codex` CLI for Attaché tests (generated by create-fake-codex-home.py,
INF-250). Mimics the real CLI's verified resume contract exactly:

  codex exec resume --skip-git-repo-check --json <sessionId> <text>

Success: JSONL thread events on stdout (a "thread.started" then an
"item.completed" agent_message, per TwoWayDeliveryAdapters.swift's
codexEvidence(fromStdout:)), exit 0, and the resumed turn appended to the
on-disk session file. Unknown/stale session id: plain-text stderr message,
exit 1, empty stdout. Do not hand-edit; regenerate via
create-fake-codex-home.py.

$CODEX_HOME (AgentResumeDeliveryAdapter's default spawn does not override it,
unlike $HOME) points at the disposable home created by
create-fake-codex-home.py; the fixture manifest lives at
<that>/attache-fake-codex-fixtures.json.

Session id and instruction text are always the last two arguments: Attaché
always calls `exec resume --skip-git-repo-check --json <id> <text>` (see
resumeArguments in TwoWayDeliveryAdapters.swift).
"""
import json
import os
import sys
import uuid
from pathlib import Path


def fake_home():
    override = os.environ.get("CODEX_HOME")
    if override:
        return Path(override)
    return Path(os.environ.get("HOME", str(Path.home()))) / ".codex"


def manifest_path():
    return fake_home() / "attache-fake-codex-fixtures.json"


def load_manifest():
    try:
        return json.loads(manifest_path().read_text(encoding="utf-8"))
    except Exception:
        return {}


def append_turn(session_file, text, reply_text):
    lines = [
        json.dumps(
            {"type": "response_item", "payload": {"type": "message", "role": "user", "content": [{"text": text or ""}]}},
            separators=(",", ":"),
        ),
        json.dumps(
            {
                "type": "response_item",
                "payload": {"type": "message", "role": "assistant", "phase": "final_answer", "content": [{"text": reply_text}]},
            },
            separators=(",", ":"),
        ),
    ]
    with open(session_file, "a", encoding="utf-8") as f:
        f.write("\\n".join(lines) + "\\n")


def main():
    argv = sys.argv[1:]
    session_id = argv[-2] if len(argv) >= 2 else None
    text = argv[-1] if argv else None

    manifest = load_manifest()
    session_file = manifest.get(session_id) if session_id else None

    if not session_id or not session_file or not Path(session_file).exists():
        sys.stderr.write(f"No conversation found matching id: {session_id}")
        sys.exit(1)

    reply_text = f"DONE: {text}" if text else "DONE"
    append_turn(session_file, text, reply_text)

    thread_id = str(uuid.uuid4())
    sys.stdout.write(json.dumps({"type": "thread.started", "thread_id": thread_id}, separators=(",", ":")) + "\\n")
    sys.stdout.write(
        json.dumps({"type": "item.completed", "item": {"type": "agent_message", "text": reply_text}}, separators=(",", ":")) + "\\n"
    )
    sys.exit(0)


if __name__ == "__main__":
    main()
'''


def iso(dt):
    return dt.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def write_session(path, session_id, cwd, title, body, ready_token):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        {
            "type": "session_meta",
            "payload": {
                "id": session_id,
                "cwd": cwd,
            },
        },
        {
            "type": "response_item",
            "payload": {
                "type": "message",
                "role": "user",
                "content": [{"text": title}],
            },
        },
        {
            "type": "response_item",
            "payload": {
                "type": "message",
                "role": "assistant",
                "phase": "final_answer",
                "content": [{"text": body}],
            },
        },
    ]
    if ready_token:
        lines.append(
            {
                "type": "response_item",
                "payload": {
                    "type": "message",
                    "role": "assistant",
                    "phase": "final_answer",
                    "content": [{"text": ready_token}],
                },
            }
        )
    path.write_text("\n".join(json.dumps(line, separators=(",", ":")) for line in lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Create a disposable fake Codex home for Attaché smoke tests.")
    parser.add_argument("--home", required=True)
    parser.add_argument("--nonce", required=True)
    parser.add_argument("--count", type=int, default=1)
    parser.add_argument("--needle", default="")
    parser.add_argument("--target-title", default="")
    parser.add_argument("--large-target", action="store_true")
    args = parser.parse_args()

    home = Path(args.home)
    sessions = home / "sessions"
    archived = home / "archived_sessions"
    automations = home / "automations"
    for directory in [sessions, archived, automations]:
        directory.mkdir(parents=True, exist_ok=True)
    (home / "session_index.jsonl").write_text("", encoding="utf-8")
    (home / "config.toml").write_text(
        'sandbox_mode = "read-only"\napproval_policy = "never"\nmodel_reasoning_effort = "low"\n',
        encoding="utf-8",
    )

    count = max(1, args.count)
    target_index = min(count - 1, max(0, count // 2))
    now = datetime.now(timezone.utc)
    day_dir = sessions / now.strftime("%Y") / now.strftime("%m") / now.strftime("%d")
    cwd = f"/tmp/attache-fake-codex-{args.nonce}"
    needle = args.needle or f"ATTACHE_LOAD_NEEDLE_{args.nonce}"
    target_title = args.target_title or f"Load smoke target {args.nonce}"
    target_session_id = ""
    target_session_file = ""

    index_lines = []
    manifest = {}
    for i in range(count):
        session_id = str(uuid.uuid4())
        updated = now - timedelta(seconds=i)
        prefix = updated.strftime("rollout-%Y-%m-%dT%H-%M-%S")
        path = day_dir / f"{prefix}-{session_id}.jsonl"
        if i == target_index:
            title = target_title
            filler = " ".join(f"large-transcript-{n}" for n in range(6000)) if args.large_target else ""
            body = f"{needle} target transcript for {args.nonce}. {filler}"
            ready_token = f"ATTACHE_READY_{args.nonce}"
            target_session_id = session_id
            target_session_file = str(path)
        else:
            title = f"Load smoke background {args.nonce} {i:03d}"
            body = f"Background fake Codex transcript {i:03d} for {args.nonce}."
            ready_token = ""
        write_session(path, session_id, cwd, title, body, ready_token)
        manifest[session_id] = str(path)
        index_lines.append(
            json.dumps(
                {
                    "id": session_id,
                    "thread_name": title,
                    "updated_at": iso(updated),
                },
                separators=(",", ":"),
            )
        )

    (home / "session_index.jsonl").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    os.chmod(home / "session_index.jsonl", 0o600)
    os.chmod(home / "config.toml", 0o600)

    # INF-250: a fake `codex` executable plus a manifest (session id -> session
    # file) so it can find the right transcript to append a resumed turn to,
    # mirroring create-fake-claude-home.py's fixture manifest.
    bin_dir = home / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    fake_codex_executable = bin_dir / "codex"
    fake_codex_executable.write_text(FAKE_CODEX_SCRIPT, encoding="utf-8")
    os.chmod(fake_codex_executable, 0o700)

    manifest_file = home / "attache-fake-codex-fixtures.json"
    manifest_file.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    os.chmod(manifest_file, 0o600)

    print(
        json.dumps(
            {
                "target_session_id": target_session_id,
                "target_session_file": target_session_file,
                "target_title": target_title,
                "needle": needle,
                "fake_codex_bin_dir": str(bin_dir),
                "fake_codex_executable": str(fake_codex_executable),
                "manifest_file": str(manifest_file),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
