#!/usr/bin/env bash
# Deterministic generator for THIRD-PARTY-LICENSES (repo root).
#
# Single source of truth for the voice attributions is the Core license manifest
# (Sources/AttacheCore/PremiumVoiceLicenseManifest.swift). That manifest is
# mirrored by licenses/premium-voice-voices.json, and a Core unit test asserts
# the two decode to the same value, so they cannot drift. This script renders the
# voice section FROM that JSON, then appends the fixed upstream license texts.
# Because the JSON is the shared input and the test binds it to the Swift
# manifest, the generated file cannot diverge from what the app shows.
#
# Usage:
#   scripts/generate-third-party-licenses.sh            # write THIRD-PARTY-LICENSES
#   scripts/generate-third-party-licenses.sh --verify   # exit 1 if it is stale
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VOICES_JSON="$REPO_ROOT/licenses/premium-voice-voices.json"
OUT="$REPO_ROOT/THIRD-PARTY-LICENSES"

MODE="write"
if [[ "${1:-}" == "--verify" ]]; then
  MODE="verify"
fi

if [[ ! -f "$VOICES_JSON" ]]; then
  echo "error: missing $VOICES_JSON (the manifest mirror the voice section renders from)." >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required to render the voice section deterministically." >&2
  exit 1
fi

mit_license() {
  # $1 = copyright holder line
  cat <<EOF
MIT License

Copyright (c) $1

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF
}

section() {
  echo "================================================================================"
  echo "$1"
  echo "================================================================================"
  echo
}

render() {
  cat <<EOF
Attaché Third-Party Licenses
================================================================================

This file is generated by scripts/generate-third-party-licenses.sh. Do not edit
it by hand; edit the Core license manifest or the upstream license texts in that
script and regenerate.

Attaché Premium on-device speech is built on the pocket-tts runtime and ships
one voice, Azelma. The attributions below cover the speech engine, its build
dependencies, the voice, and the in-app updater.

EOF

  section "Voice attributions"
  python3 - "$VOICES_JSON" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
entries = sorted(data.get("entries", []), key=lambda e: e["id"])
lines = []
for e in entries:
    lines.append(f'{e["displayName"]} ({e["id"]})')
    lines.append(f'License: {"CC BY 4.0" if e["license"] == "ccBy4" else "CC0 1.0"} <{e["licenseURL"]}>')
    lines.append(e["attributionText"])
    lines.append("")
sys.stdout.write("\n".join(lines))
sys.stdout.write("\n")
PY
  echo

  section "pocket-tts / PocketTTS.cpp (speech engine)"
  mit_license "2026 VolgaGerm; portions Copyright (c) Kyutai (kyutai-labs)"
  echo

  section "ONNX Runtime (inference)"
  mit_license "Microsoft Corporation"
  echo
  echo "ONNX Runtime bundles the following components under their own licenses:"
  echo "  - Eigen, Mozilla Public License 2.0 (see below)"
  echo "  - abseil, Apache License 2.0"
  echo "  - protobuf, BSD 3-Clause License"
  echo "  - nsync, Apache License 2.0"
  echo

  section "Eigen (bundled by ONNX Runtime)"
  cat <<'EOF'
Eigen is licensed under the Mozilla Public License, v. 2.0. A copy of the MPL
2.0 is available at https://mozilla.org/MPL/2.0/. If a copy of the MPL was not
distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
The Eigen source is unmodified; no MPL-covered file is altered by Attaché.
EOF
  echo

  section "SentencePiece (tokenizer)"
  cat <<'EOF'
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

Copyright 2016 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

The full Apache License 2.0 text is available at the URL above.
EOF
  echo

  section "dr_wav (WAV decoding)"
  cat <<'EOF'
dr_wav is released into the public domain, or alternatively under the MIT No
Attribution license (MIT-0):

MIT No Attribution

Copyright (c) David Reid

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
EOF
  echo

  section "Model weights"
  cat <<'EOF'
The Attaché Premium voice model weights are licensed under the Creative Commons
Attribution 4.0 International License (CC BY 4.0),
https://creativecommons.org/licenses/by/4.0/.
EOF
  echo

  section "Sparkle (in-app updates)"
  cat <<'EOF'
Copyright (c) 2006-2013 Andy Matuschak.
Copyright (c) 2009-2013 Elgato Systems GmbH.
Copyright (c) 2011-2014 Kornel Lesiński.
Copyright (c) 2015-present Sparkle Project contributors.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Sparkle also includes bsdiff (BSD 2-Clause) and other components under permissive
licenses; see https://github.com/sparkle-project/Sparkle for details.
EOF
}

GENERATED="$(render)"

if [[ "$MODE" == "verify" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "error: $OUT is missing; run scripts/generate-third-party-licenses.sh." >&2
    exit 1
  fi
  if ! diff -u "$OUT" <(printf '%s\n' "$GENERATED") >/dev/null; then
    echo "error: THIRD-PARTY-LICENSES is stale. Regenerate with scripts/generate-third-party-licenses.sh." >&2
    diff -u "$OUT" <(printf '%s\n' "$GENERATED") >&2 || true
    exit 1
  fi
  echo "THIRD-PARTY-LICENSES is up to date."
  exit 0
fi

printf '%s\n' "$GENERATED" > "$OUT"
echo "Wrote $OUT"
