#!/usr/bin/env bash
# Deterministic generator for THIRD-PARTY-LICENSES (repo root).
#
# Single source of truth for the voice attributions is the Core license manifest
# (Sources/AttacheCore/PremiumVoiceLicenseManifest.swift). That manifest is
# mirrored by licenses/premium-voice-voices.json, and a Core unit test asserts
# the two decode to the same value, so they cannot drift. This script renders the
# voice section FROM that JSON, then appends the fixed upstream license texts.
# Because the JSON is the shared input and the test binds it to the Swift
# manifest, the generated file cannot diverge from what the app shows.
#
# Usage:
#   scripts/generate-third-party-licenses.sh            # write THIRD-PARTY-LICENSES
#   scripts/generate-third-party-licenses.sh --verify   # exit 1 if it is stale
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VOICES_JSON="$REPO_ROOT/licenses/premium-voice-voices.json"
UPSTREAM_DIR="$REPO_ROOT/licenses/upstream"
OUT="$REPO_ROOT/THIRD-PARTY-LICENSES"

MODE="write"
if [[ "${1:-}" == "--verify" ]]; then
  MODE="verify"
fi

if [[ ! -f "$VOICES_JSON" ]]; then
  echo "error: missing $VOICES_JSON (the manifest mirror the voice section renders from)." >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required to render the voice section deterministically." >&2
  exit 1
fi

# Upstream LICENSE files are checked in under licenses/upstream/ so that, once
# fetched, generation is offline and deterministic. This preflight makes a
# missing file a hard error rather than a silently truncated attribution.
UPSTREAM_FILES=(
  "PocketTTS.cpp-LICENSE"
  "pocket-tts-LICENSE"
  "onnxruntime-LICENSE"
  "sentencepiece-LICENSE"
  "dr_libs-LICENSE"
  "sparkle-LICENSE"
)
for name in "${UPSTREAM_FILES[@]}"; do
  if [[ ! -f "$UPSTREAM_DIR/$name" ]]; then
    echo "error: missing upstream license file $UPSTREAM_DIR/$name." >&2
    echo "       Re-fetch it from the component's repository (see the header)." >&2
    exit 1
  fi
done

# Emits an upstream LICENSE file verbatim, normalizing only the trailing newline
# so the blank-line section separator renders consistently whether or not the
# upstream file ends in a newline.
verbatim() {
  # $1 = file name under licenses/upstream
  local file="$UPSTREAM_DIR/$1"
  cat "$file"
  # Append a newline only when the file does not already end in one, so a body
  # always ends with exactly one newline before the section separator.
  if [[ -n "$(tail -c1 "$file")" ]]; then
    echo
  fi
  return 0
}

section() {
  echo "================================================================================"
  echo "$1"
  echo "================================================================================"
  echo
}

render() {
  cat <<EOF
Attaché Third-Party Licenses
================================================================================

This file is generated by scripts/generate-third-party-licenses.sh. Do not edit
it by hand; edit the Core license manifest (voice attributions) or the upstream
license texts under licenses/upstream/, then regenerate.

Attaché Premium on-device speech is built on the pocket-tts runtime and ships
one voice, Azelma. The attributions below cover the speech engine, its build
dependencies, the voice, and the in-app updater. Each component's license text
is reproduced verbatim from its upstream source in licenses/upstream/.

EOF

  section "Voice attributions"
  python3 - "$VOICES_JSON" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
entries = sorted(data.get("entries", []), key=lambda e: e["id"])
lines = []
for e in entries:
    lines.append(f'{e["displayName"]} ({e["id"]})')
    lines.append(f'License: {"CC BY 4.0" if e["license"] == "ccBy4" else "CC0 1.0"} <{e["licenseURL"]}>')
    lines.append(e["attributionText"])
    lines.append("")
sys.stdout.write("\n".join(lines))
sys.stdout.write("\n")
PY
  echo

  section "PocketTTS.cpp (speech engine)"
  verbatim "PocketTTS.cpp-LICENSE"
  echo

  section "pocket-tts (speech engine)"
  verbatim "pocket-tts-LICENSE"
  echo

  section "ONNX Runtime (inference)"
  verbatim "onnxruntime-LICENSE"
  echo
  echo "ONNX Runtime bundles the following components under their own licenses:"
  echo "  - Eigen, Mozilla Public License 2.0 (see below)"
  echo "  - abseil, Apache License 2.0"
  echo "  - protobuf, BSD 3-Clause License"
  echo "  - nsync, Apache License 2.0"
  echo

  section "Eigen (bundled by ONNX Runtime)"
  cat <<'EOF'
Eigen is licensed under the Mozilla Public License, v. 2.0. A copy of the MPL
2.0 is available at https://mozilla.org/MPL/2.0/. If a copy of the MPL was not
distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
The Eigen source is unmodified; no MPL-covered file is altered by Attaché.
EOF
  echo

  section "SentencePiece (tokenizer)"
  verbatim "sentencepiece-LICENSE"
  echo

  section "dr_wav (WAV decoding, from dr_libs)"
  verbatim "dr_libs-LICENSE"
  echo

  section "Model weights"
  cat <<'EOF'
The Attaché Premium voice model weights are licensed under the Creative Commons
Attribution 4.0 International License (CC BY 4.0),
https://creativecommons.org/licenses/by/4.0/.
EOF
  echo

  section "Sparkle (in-app updates)"
  verbatim "sparkle-LICENSE"
}

GENERATED="$(render)"

if [[ "$MODE" == "verify" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "error: $OUT is missing; run scripts/generate-third-party-licenses.sh." >&2
    exit 1
  fi
  if ! diff -u "$OUT" <(printf '%s\n' "$GENERATED") >/dev/null; then
    echo "error: THIRD-PARTY-LICENSES is stale. Regenerate with scripts/generate-third-party-licenses.sh." >&2
    diff -u "$OUT" <(printf '%s\n' "$GENERATED") >&2 || true
    exit 1
  fi
  echo "THIRD-PARTY-LICENSES is up to date."
  exit 0
fi

printf '%s\n' "$GENERATED" > "$OUT"
echo "Wrote $OUT"
